This notebook is intended for learning purposes only. I will use it to learn/ try NumPy (Numerical Python) package. 


In [15]:
# Importing the numpy package
import numpy as np

Python is dynamically typed programming language

In [20]:
result = 0
for i in range(100):
    result += i

In [21]:
L = list(range(100))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [22]:
import array

In [23]:
A = array.array('i', L)
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])


### Creating Array from Python Lists

we can use `np.array` to create arrays from python lists. <strong>Remember</strong>, NumPy are constrained to arrays that all contain the same type. To explicitly setup the type of array, one can use the `dtype` keyword.

In [34]:
# Creating an array
A = np.array([2,1,3,4,5])

# To explicitly setup the type of array, one can use the `dtype` keyword.
A1 = np.array([1,23,4.2], dtype='float32')
print('A1: ',  A1)

# Unline python lists, NumPy arrays can be explicitly mutlidimensional.
A2 = np.array([range(i, i + 3) for i in [2, 4, 6]])
print('A2: ', A2)

A1:  [ 1.  23.   4.2]
A2:  [[2 3 4]
 [4 5 6]
 [6 7 8]]


### Creating Arrays fron Scratch

Using routines built into NumPy. `np.array()` `np.ones()` `np.zeros()` `np.full` `np.arange()`

Create 3X2 floating-point array of ones. Notice how we pass a `tuple` to the NumPy `ones()` method.
`ones_array = np.ones((3, 2), dtype = 'float')`

In [65]:
# Create a length-10 integer array filled with zeros
zeros_array = np.zeros(10, dtype='int')
print(zeros_array )

# Create 3X2 floating-point array of ones. Notice how we pass a tuple to the NumPy ònes` method.
ones_array = np.ones((3, 2), dtype = 'float')
print(ones_array)

# Create a 3X5 array filled with 3.23
full_array = np.full((3, 5), 3.23)
print(full_array)

# Creating an array containing sequence starting at 0 ending at 20 steps by 2
seq_array = np.arange(0, 20, 2)
print(seq_array)

# Create an array of five values evenly spaced between 0 and 1
even_spaced_array = np.linspace(0, 1, 5)
print(even_spaced_array)

# Create 3X3 array of unformally distributed random values between 0 and 1
rand_array = np.random.random((3,3))
print('random array of values between 0 and 1: ', rand_array)

# Create a 3X3 array of normally distributed random values with mean eqausl
normal_array = np.random.normal(0, 1, (3, 3))
print('normally distributed random values with mean = 0 and sd = 1: ', normal_array)

# Create a 3X3 array of random integers in the interval [0, 10)
random_int_array = np.random.randint(0, 10, (3, 3))
print('random int array: ', random_int_array)

# Create the 3X3 identity array 
eye_array = np.eye(3)
print('eye_array: ')
print(eye_array)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3.23 3.23 3.23 3.23 3.23]
 [3.23 3.23 3.23 3.23 3.23]
 [3.23 3.23 3.23 3.23 3.23]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
random array of values between 0 and 1:  [[0.0632063  0.32300116 0.19654415]
 [0.22966723 0.53639549 0.41792491]
 [0.26224887 0.70622746 0.39866098]]
normally distributed random values with mean = 0 and sd = 1:  [[ 1.13439738  0.20272306 -0.3108142 ]
 [-0.99537118 -0.77198401  0.60450722]
 [-1.01777316 -0.72886497 -0.64714294]]
random int array:  [[8 3 4]
 [6 7 5]
 [2 0 7]]
eye_array: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### NumPy Standard Data Types

NumPy arrays contains value of a single type, so it is important to have a detailed knowledge of those types and their limitations.


### The Basics of NumPy Arrays

Data manipulation in Python is synonymous with NumPy array manipulation. 

Array manipulations can be divided down to five categories:

1. <strong>Attributes of arrays</strong>
2. <strong>Indexing of arrays</strong>
3. <strong>Slicing of arrays</strong>
4. <strong>Reshaping of arrays</strong>
5. <strong>Joining and splitting of arrays</strong>
